### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by LostSoulfly** [StrikeOrg/ulterius-server#12]
I'm running Windows 10 Pro, 64-bit on a Surface Pro 4.

I suspect I am unable to login because my machine is joined to a domain and the login prompt does not give me the option to change the login name. Also, the account I use is not local to the machine so it would likely need to be validated with a domain controller.

Can we supply a default login/password to allow access?

**Comment by andrewmd5** [comment]
Hi @LostSoulFly please try this new version and let me know if it works 

https://ulterius.xyz/downloads/ulterius1.0.0.1beta.zip

**Comment by healingtaco** [comment]
I am having the same issue, and I just reinstalled the 1.0.0.1. Still having the issue.

**Comment by LostSoulfly** [comment]
No fix here, either.

**Comment by andrewmd5** [comment]
https://ulterius.xyz/downloads/LoginTester.exe

@healingtaco and @LostSoulFly 

Give this a try and let me know which attempts it says True or False on

**Comment by healingtaco** [comment]
True
testing using auto domain
False

**Comment by LostSoulfly** [comment]
![image](https://cloud.githubusercontent.com/assets/9120519/17524842/337762ec-5e2e-11e6-91e9-763bb01de0bc.png)

**Comment by andrewmd5** [comment]
[LoginTester.zip](https://github.com/Ulterius/server/files/409458/LoginTester.zip)

Try this @LostSoulFly

**Comment by LostSoulfly** [comment]
False local
False
testing using auto directory
False auto directory

**Comment by andrewmd5** [comment]
@healingtaco I have your issue fixed, once I've managed to fix @LostSoulFly it should all be covered.

How is your username formatted for the domain @LostSoulFly

**Comment by healingtaco** [comment]
Thank you sir!

**Comment by andrewmd5** [comment]
[LoginTester.zip](https://github.com/Ulterius/server/files/409479/LoginTester.zip)

@LostSoulFly this should work

**Comment by LostSoulfly** [comment]
I ask that you remove this post once you've obtained the information. Thanks!

**Comment by andrewmd5** [comment]
@LostSoulFly 

Got it, can you try the program in my previous post.

**Comment by LostSoulfly** [comment]
False local
False

If I input an incorrect password it takes 4-5x longer to generate the above, but the correct password is almost instant.

**Comment by andrewmd5** [comment]
[LoginTester.zip](https://github.com/Ulterius/server/files/409537/LoginTester.zip)

@LostSoulFly this will attempt to validate your controller, let me know what it prints.

**Comment by LostSoulfly** [comment]
False local
Default-First-Site-Name

**Comment by andrewmd5** [comment]
@LostSoulFly Awesome, found the fix. Pushing changes in a second

**Comment by andrewmd5** [comment]
@LostSoulFly @healingtaco 

https://ulterius.xyz/downloads/ulterius1.0.0.1beta.zip

see if this fixes your login issues

**Comment by healingtaco** [comment]
Works like a charm!
