### ISSUE TITLE
Only able to connect to the client at local network

### ISSUE THREAD

**Issue by anpengxiang** [StrikeOrg/ulterius-server#13]
I'm running Windows 7 Pro, 64-bit on a ThinkPad T440s.

There are no issue of connecting to the client when using a computer connected to the same network, but unable to connect using any other network. The client currently sits on 192.168.2.57:22006

**Comment by zeon** [comment]
Yes, the use case scenario would mostly be outside of home since you don't really need to remote access your PC when you are at home. Public accessibility is a must.

**Comment by andrewmd5** [comment]
Have you tried connecting through the public IP? Google "Whats my ip" on the host machine and then connect to the webserver using that ip. 

If you're still unable to connect, you'll need to forward the ports as UPNP wasn't able too.

**Comment by zeon** [comment]
which ports to open?

2016-08-10 14:07 GMT+08:00 Andrew Sampson notifications@github.com:

**Comment by andrewmd5** [comment]
@zeon 

22006 - web server
22007 - api
22008 - terminal
22009 - screenshare

**Comment by anpengxiang** [comment]
Does not work through public IP, are there any alternative to port fowarding? In some cases like mine, the user does not have router access the forward the ports.

**Comment by andrewmd5** [comment]
@anpengxiang If UPNP is not enabled/supported on the router, there isn't much that can be done. The only other option is port forwarding. Contact your administrator and ask them to forward the following ports or enable UPNP. 

Also double check your firewall rules and make sure the ulterius ports are opened.

**Comment by sry9681** [comment]
You could set up a vpn into your home network which would bypass the port forwarding issue that you don't have access to.

**Comment by cjchild** [comment]
Not sure if it's the same issue - I can access the Ulterius Client internally and log in with no issue, however remotely I get as far as the Ulterius Client page, but can't seem to connect to my machine.  Receive the error 'Failed to connect, host invalid' no matter what machine name, IP or DNS alias I try.  UPNP is enabled, ports are forwarded thru, firewall is open.

Do I just have the dumb and failed to enter the correct info somewhere?  I've tried turning on 'Skip network hostname resolve' with no change.

**Comment by ghost** [comment]
I have ports 22006-22009 forwarded to my 'server', but am also only able to connect to the client webpage. As soon as I try to connect to the server, it just hangs at 'connecting to server'. 

I have tried using the external IP address for the server, localhost, and the internal IP address of the server with no luck. 

Works locally, but not over the internet.

**Comment by andrewmd5** [comment]
@Kukaw I had this issue when I setup a reverse proxy, I had to clear my browser cache for some strange reason.
