### ISSUE TITLE
Blank command window when opening for the first time.

### ISSUE THREAD

**Issue by sry9681** [StrikeOrg/ulterius-server#14]
After installing for the first time and clicking the executable to open for the first time, the command window opens to run the local server and it just stays blank. It has the blinking cursor on the top left but nothing else happens. It just stays blank. 

I tried looking for logs but nothing is created because it hasn't successfully run anything.

**Comment by andrewmd5** [comment]
Hi @sry9681 did you use the latest installer from https://ulterius.xyz/

You may also try installing .NET 4.6.1
