### ISSUE TITLE
High Memory Usage

### ISSUE THREAD

**Issue by Yousefjb** [StrikeOrg/ulterius-server#15]
the memory used by server reaches 450 MB when the first client connects. 
i believe you can reduce it to at max 100 MB 
Thanks for your work

**Comment by Js41637** [comment]
# 10MB or bust

**Comment by riotpunch** [comment]
If the peak usage is > 5MB, you have failed.

**Comment by luigiplr** [comment]
HOW WILL I RUN THIS ON MY COMMODORE 64.

> unacceptable.

**Comment by andrewmd5** [comment]
@Yousefjb 

The first time the server runs it is indexing all your files, this causes high ram usage, garbage collection will eventually free this memory. Restarting the server will result in lower memory. 

Optimizations to the  [file-search](https://github.com/Ulterius/file-search) repo are needed.

**Comment by Yousefjb** [comment]
@Codeusa  Yes you are right, now it ranges between 50-100 MB 
for the other guys above, what hell is wrong with you ? i am comparing Ulterius to other alternatives which uses less resources
