### ISSUE TITLE
Avast Antivirus 

### ISSUE THREAD

**Issue by svg-frog** [StrikeOrg/ulterius-server#16]
Avast detects setup.exe as a Trojan.

What aspect might be influencing that rating?

**Comment by andrewmd5** [comment]
Avast is a terrible piece of software, thats about it.

**Comment by jebeld17** [comment]
So is this why _Kaspersky_ is detecting Ulterius Server.exe as a trojan, Trojan.MSIL.Crypt.dcyu, as well?

![capture](https://cloud.githubusercontent.com/assets/9492083/25812939/eaefd764-33e5-11e7-9ce9-2ace0e3ec149.PNG)

**Comment by scramble45** [comment]
[VirusTotal Link](https://www.virustotal.com/en/file/87ae371d0ce6679b91c4d8549ef022157d5b35e2024b1ee762a7c80614f4a822/analysis/1506898193/)
