### ISSUE TITLE
Server failing to restart or start on bootup.

### ISSUE THREAD

**Issue by pollock83** [StrikeOrg/ulterius-server#17]
The server does not start up when my computer starts up and when I select 'Restart Server' in the client, the server correctly shuts down, but does not start back up again unless I do it manually.

**Comment by pollock83** [comment]
Just a quick extra note, I have double checked msconfig and Ulterius is set to start on bootup, but isn't starting on bootup.

**Comment by pldmgg** [comment]
+1 I encountered the same problem
