### ISSUE TITLE
Running PowerShell via Ulterius Client (UC) Terminal hangs UC (Terminal)

### ISSUE THREAD

**Issue by pldmgg** [StrikeOrg/ulterius-server#19]
(Just need to say, this is an amazing product and thank you so much for spending the time developing it!)

Here's a record of what I did step by step. I also attached server.log at the bottom for additional info.
- Ulterius Server Host is 192.168.2.22
- Ulterius Client machine is 192.168.2.31
- Process IDs and Parent Process Ids Discovered Using the Following Command on Ulterius Server Host in a normal RDP session using cmd prompt
  wmic process get Caption,ParentProcessId,ProcessId

BEGIN Progression of Events starting with launching Ulterius Server
- bootstrapper.exe 908 which spawns... Ulterius Server.exe 3672
- which spawns... conhost.exe 3268
- From Windows client machine (i.e. 192.168.2.31), launch Google Chrome (v52.0.2743.116 m) and browse to http://192.168.2.22:22006
- After logging in with domain credentials from Google Chrome on 192.168.2.31, navigate to "Terminal" in Ulterius Client
- Navigating to Terminal tab in Ulterius client starts cmd.exe 520 which spawns... conhost.exe 2868
- In Ulterius Client using Terminal cmd.exe 520, after using ulterius-auth to authenticate, run the following:
  (Expectation is to get an interactive powershell prompt in current shell)
  C:>powershell.exe -noprofile
- cmd.exe 520 then spawns... powershell.exe 1976
- ...but in the Ulterius Client terminal, cmd prompt is hung (no keyboard inputs work), with nothing returned after "C:>powershell.exe -noprofile"
- killed cmd.exe 520 using Task Manager in Ulterius Client
- Refreshed wepbage in Chrome
- In RDP session on Ulterius Server host (192.168.2.22), confirmed in Task Manager that cmd.exe 520 is gone went back to "Terminal" tab in Ulterius Client
- which spawns... cmd.exe 4016
- which spawns... conhost 1596
- In Ulterius Client using Terminal cmd.exe 4016, after using ulterius-auth to authenticate, run the following:
- (Expectation is to get an interactive powershell prompt in current shell)
  C:>powershell.exe -noprofile
- cmd.exe 4016 then spawns... powershell.exe 76
- This time the Windows PowerShell banner is returned:

Windows PowerShell
Copyright (C) 2014 Microsoft Corporation. All rights reserved
- ... but doesn't get to the actual interactive prompt. Ulterius terminal is hung (no keyboard inputs work)

[Ulterius_Server_Log.txt](https://github.com/Ulterius/server/files/420770/Ulterius_Server_Log.txt)

**Comment by andrewmd5** [comment]
Hi @pldmgg currently the powershell portion of the Ulterius server is not present in the client, we actually have powershell support but it hasn't been implemented from the frontend, it should be done fairly soon.  

Thank you for the report.

**Comment by pldmgg** [comment]
Awesome! Thanks so much for developing this!

**Comment by andrewmd5** [comment]
@pldmgg check out the latest version, powershell has been implemented
