### ISSUE TITLE
Silent install for Ulterius Server package

### ISSUE THREAD

**Issue by ktos** [StrikeOrg/ulterius-server#21]
I would love to create a [Chocolatey](https://chocolatey.org) (package manager for Windows) package for Ulterius, but there is no silent install option in the installer.

I even tried to extract the MSI and install from there (as msiexec allows /quiet and /passive installation options), however "This package may be run only from bootstraper" is shown :(

Silent install mode would be interesting for sysadmins.

**Comment by andrewmd5** [comment]
@ktos Does /qn not work?

```
setup.exe /qn
```

**Comment by ktos** [comment]
Works, tried /s and /silent, forgot about /q, thanks.
