### ISSUE TITLE
System information not loading

### ISSUE THREAD

**Issue by skjetne** [StrikeOrg/ulterius-server#23]
All other functions are working except for this. 
Server is running as admin, but still no luck.

**Comment by andrewmd5** [comment]
You need to post the output of server.log found at \AppData\Roaming\Ulterius\Ulterius Server and also any exceptions occurring from the excretions folder

**Comment by skjetne** [comment]
http://pastebin.com/wPHJuCuG

I can't find any excretions folder though

**Comment by andrewmd5** [comment]
What does the system information loading bar get stuck on?

**Comment by skjetne** [comment]
Most of the time it just says "Loading system information ", but i've seen it stuck at network and graphics card.

Win 10 bail 14393.51.

motherboard and cpu are Msi H110i pro and i5 6400

**Comment by andrewmd5** [comment]
Turn off "resolve network names" in the settings

**Comment by skjetne** [comment]
Cool

Btw. is this normal behavior?

![2016-08-18 at 13 04](https://cloud.githubusercontent.com/assets/17202764/17771635/60d25680-6544-11e6-8681-be992468aa5e.png)

**Comment by andrewmd5** [comment]
Did turning off hostname resolve fix the issue with loading?

And thats just a visual bug, it will be fixed soon.

**Comment by skjetne** [comment]
Nope, it's still loading as of now. Opened it 8 minutes ago

**Comment by andrewmd5** [comment]
Do you have any protected drives by any chance?

**Comment by skjetne** [comment]
Nope. All windows settings are stock.

**Comment by andrewmd5** [comment]
@skjetne see if the new update helped
