### ISSUE TITLE
Ulterius server

### ISSUE THREAD

**Issue by Stonedestroyer** [StrikeOrg/ulterius-server#26]
When starting ulterius server, the dos prompt keeps opening and closing bootstrapper.exe, 
System is windows server 2008 r2 x64

**Comment by kdanthony** [comment]
I have this same exact issue, is there a solution that caused it to be closed?

**Comment by andrewmd5** [comment]
@kdanthony Try installing the latest .NET

**Comment by Stonedestroyer** [comment]
The problem I had was the shortcut was leading to bootstrapper exe file instead of the ulterius, so I went to program directory and launched manually.

**Comment by andrewmd5** [comment]
@Stonedestroyer this is because Bootstrapper handles updating the server. What are your system settings?

**Comment by Stonedestroyer** [comment]
What do you mean by system settings?

**Comment by kdanthony** [comment]
Installed .net 4.6.2 (4.6.1 was already installed) and no change. Running 'Ulterius Server.exe' directly just quits immediately. Windows 2012 R2.

**Comment by andrewmd5** [comment]
@kdanthony @Stonedestroyer this fix is now live, download the latest installer and try that.
