### ISSUE TITLE
ArgumentOutOfRangeException's on Start-up

### ISSUE THREAD

**Issue by mythral** [StrikeOrg/ulterius-server#33]
I am getting `ArgumentOutOfRangeException`'s  after starting Terminal API and after Starting notify icon

Log: [http://pastebin.com/rKSJ1qA0](http://pastebin.com/rKSJ1qA0)

**Comment by andrewmd5** [comment]
@Mythral is it actually blocking the server from working normally?

**Comment by mythral** [comment]
I'm assuming it is, I can't access the server from the client and that's the only error in the log.

**Comment by andrewmd5** [comment]
Opening the client from the tray icon doesn't produce the web page?

**Comment by mythral** [comment]
The client opens, however when I try to logon it hangs

**Comment by andrewmd5** [comment]
Alright I'll get a fix out in a bit
