### ISSUE TITLE
System Information and Filesystem only show 6 of 7 drives

### ISSUE THREAD

**Issue by LenAnderson** [StrikeOrg/ulterius-server#36]
I am connecting to a Windows Home Server 2011 x64 with 7 hard drives (C, D, E, F, G, H, I). Only the first 6 are listed on the System Information and the Filesystem screens. The 7th is accessible if I enter the drive letter in the file bar / path bar of the Filesystem screen.

**Comment by andrewmd5** [comment]
What kind of drive is it? (Network, physical, etc) 

Check your server.log file or the Exceptions folder in app data for messages

**Comment by LenAnderson** [comment]
A physical drive, as are all the other drives. The only difference I can think of is that it has 6TB instead of 3TB.

Nothing in the server.log regarding the drives. This is the content of server.log after starting the server, logging in with a client and opening the Filesystem screen:

```
Logs Ready
Set Startup
Loading Webcams
0 cameras loaded
Setting up HTTP Server
Web Server is running on this port: 22006
Creating system service
Api Server started at 0.0.0.0
Starting Terminal API
File Database Ready
Terminal Server bound to 0.0.0.0:22008
Trying to forward ports
Starting notify icon
Ports forwarded!
Connection from <myIP>:<myPort>
Manager started for 22009
UlteriusServer.TerminalServer.Messaging.TerminalControl.Requests.AesHandshakeRequest
UlteriusServer.TerminalServer.Messaging.TerminalControl.Requests.CreateTerminalRequest
```

I have no Exceptions folder in app data but I do have one called Traces. An empty file `Trace-13-17-18 PM 1473247038.log` was created while doing the above steps.

**Comment by andrewmd5** [comment]
Hey @LenAnderson test the new version and see if this issue is still around. You can download the new installer or kill and start Ulterius again.

**Comment by LenAnderson** [comment]
Works perfectly now!

Did you also change something related to screen sharing? Yesterday I could only get it to work if I was connecting from the same machine. Using a computer on the same network or through the internet I was not able to share the screen and now it just works :)
