### ISSUE TITLE
System information

### ISSUE THREAD

**Issue by Cyndro** [StrikeOrg/ulterius-server#38]
Windows 10 user here. The System information tab either takes an excessively long time to load or never loads. I've tried it many times now and I just get a loading bar, I've let it sit for a few minutes and nothing ever shows up.

**Comment by Cyndro** [comment]
Same issue with the Camera's tab actually.

**Comment by andrewmd5** [comment]
Can you check the clients web console for any messages? I'll also need to see the server.log file.

**Comment by Cyndro** [comment]
I will tonight.. I tried using the restart server function (I'm at work right now) and who knows what happened on the other end, but the server never came back to life.

**Comment by Cyndro** [comment]
Also, the File System page has the same issue.

**Comment by andrewmd5** [comment]
@Cyndro sorry for all the trouble, I'll see whats up when you've posted the logs.

**Comment by Cyndro** [comment]
had to change the extension to .txt since .log isn't supported but here it is:
[server.txt](https://github.com/Ulterius/server/files/460765/server.txt)
not sure what you mean by web console? but the Terminal shows:
Please Login to continue (ulterius-auth)
Microsoft Windows [Version 10.0.14393](c) 2016 Microsoft Corporation. All rights reserved.
C:>

Full breakdown: 
Under Task Manager I can see the processes, but the stats on the right just say loading forever
Under System Information/Cameras/Filesystem I get nothing but loading forever
Screen Share sorta works, but I get black screens when a UAC prompt is displayed and sometimes have to click the connect button a few times or reload the page before it works.

**Comment by andrewmd5** [comment]
Download the latest installer and see if your problem goes away  1.1.2

**Comment by rozza-m** [comment]
Having _exact;y_ the same issue. Upgraded to 1.1.2 and it's still the same. (by the way, did you know that the installer boots you out if you try to install a new version and you have to remove the current version from Add/Remove Programs? Bleh)

<details>
  <summary>

Log (click to expand)</summary>



```
Logs Ready
Set Startup
Setting up HTTP Server
Web Server is running on this port: 22006
Creating system service
Object reference not set to an instance of an object.
   at UlteriusServer.Api.Services.System.SystemService.SetNetworkInformation() in D:\Documents\StrikeTaskManager\RemoteTaskServer\Api\Services\LocalSystem\SystemService.cs:line 63
   at UlteriusServer.Api.Services.System.SystemService.Start() in D:\Documents\StrikeTaskManager\RemoteTaskServer\Api\Services\LocalSystem\SystemService.cs:line 42
File Database Ready
Api Server started at 0.0.0.0
Starting Terminal API
Terminal Server bound to 0.0.0.0:22008
Trying to forward ports
Starting notify icon
Ports forwarded!
Connection from 192.168.137.1:51350
Connection from 192.168.1.14:51351
Session '88f2fab7-0cdc-42d8-89ca-b8630ba276f2' with connection '60a66a6c-021a-41fd-8e41-386fab453a64' disconnected
Manager started for 22009
UlteriusServer.TerminalServer.Messaging.TerminalControl.Requests.AesHandshakeRequest
Manager started for 22010
UlteriusServer.TerminalServer.Messaging.TerminalControl.Requests.CreateTerminalRequest
Session 'c84295db-6b4b-46c2-998f-5259ffcdea69' with connection '3aece124-76d6-4c36-b36b-bbb309bd2351' disconnected
Disconnection from 192.168.137.1:51350
Disconnection from 192.168.1.14:51356
Session '88f2fab7-0cdc-42d8-89ca-b8630ba276f2' with connection '8202e8ba-4050-40cb-9549-e3c254c22857' disconnected
Connection from 192.168.1.14:51367
Manager started for 22010
Manager started for 22009
UlteriusServer.TerminalServer.Messaging.TerminalControl.Requests.AesHandshakeRequest
UlteriusServer.TerminalServer.Messaging.TerminalControl.Requests.CreateTerminalRequest
```

</details>

Also, I don't have a D:\Documents....

**Comment by Cyndro** [comment]
Not sure if I mentioned this yet, but I also often see a red pop-up in the bottom right that says "Failed to connect. Invalid Host." shortly after click on the sections on the left that don't work (listed above). I'll update to 1.1.2 once I get home tonight.

**Comment by andrewmd5** [comment]
Updated again, give it another go.

Also from your web developer console (press f12 when the client is open) type the following

```
localStorage.clear();
```

**Comment by Cyndro** [comment]
1.1.4 has cleared up all the issues, everything loads instantly now.
