### ISSUE TITLE
Ulterius Sever has stopped working Newtonsoft.json

### ISSUE THREAD

**Issue by ewsclass66** [StrikeOrg/ulterius-server#39]
Whenever i try to start the server, i get a stopped working dialogue box. I am running Server 2012 R2 with the latest .NET framework and updates. Here is the detail problem information. Any help would be much appreciated.
Problem signature:
  Problem Event Name:   CLR20r3
  Problem Signature 01: Ulterius Server.exe
  Problem Signature 02: 1.1.0.0
  Problem Signature 03: 57d0d80d
  Problem Signature 04: Newtonsoft.Json
  Problem Signature 05: 9.0.0.0
  Problem Signature 06: 575e9365
  Problem Signature 07: 1cd
  Problem Signature 08: 178
  Problem Signature 09: Newtonsoft.Json.JsonReader
  OS Version:   6.3.9600.2.0.0.400.8
  Locale ID:    2057
  Additional Information 1: 114c
  Additional Information 2: 114c75c53e6406fcf41554652316b63c
  Additional Information 3: 0b38
  Additional Information 4: 0b38f4b9ddfda81c6080e2ea176e8c55

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by andrewmd5** [comment]
Can you check \AppData\Roaming\Ulterius\Ulterius Server\Logs\ and copy the contents of the exception file here (or upload it)

**Comment by ewsclass66** [comment]
Hello, If you received my email then please disregard this, it is just a re upload just in case you didn't get it. This is the log files that you specified in the comments above.

[Logs.zip](https://github.com/Ulterius/server/files/462250/Logs.zip)

**Comment by andrewmd5** [comment]
Hi @ewsclass66 can you try deleting your Config.json file

**Comment by ewsclass66** [comment]
Thanks its working now, should have tried that before
