### ISSUE TITLE
This is our code

### ISSUE THREAD

**Issue by ghost** [StrikeOrg/ulterius-server#4]
Please cease and desist immediately.

**Comment by andrewmd5** [comment]
No we didn't but have a chip. 
![](https://45.media.tumblr.com/866ad566ac45add3b2405e8ace8591d0/tumblr_nko3h2S05Y1qgcra2o1_500.gif)

**Comment by luigiplr** [comment]
![](https://i.imgflip.com/x9hpi.jpg)

**Comment by Js41637** [comment]
http://i.imgur.com/AFR91We.gif

**Comment by andrewmd5** [comment]
Dude cease and desist those cows

**Comment by Js41637** [comment]
![](http://i.imgur.com/AFR91We.gif)

**Comment by jaruba** [comment]
![boobs-fail-great-gif_o_112924](https://cloud.githubusercontent.com/assets/1777923/12281248/17fb9032-b99d-11e5-8ce3-7a3d8d43b991.gif)

**Comment by Js41637** [comment]
![](http://i.imgur.com/rqWYJUb.jpg)

**Comment by andrewmd5** [comment]
![stop](https://i.imgur.com/2HmGTpa.gif)

**Comment by luigiplr** [comment]
@jaruba ![](http://i.imgur.com/N7OJVxB.jpg)

**Comment by andrewmd5** [comment]
![st](https://31.media.tumblr.com/469a961e38dbf6619ba5f482436c8fcb/tumblr_mvy9hdSzdX1slvokqo1_400.gif)

**Comment by Js41637** [comment]
![](http://i.imgur.com/FSdjW0F.gif)

**Comment by andrewmd5** [comment]
![](https://i.imgur.com/TYIrkr1.gif?noredirect)

**Comment by jaruba** [comment]
![giphy 4](https://cloud.githubusercontent.com/assets/1777923/12281298/9e1ba314-b99d-11e5-86d5-01366830fe39.gif)

**Comment by luigiplr** [comment]
`/thread` :
![](https://media.giphy.com/media/V8uTrIni6LzgI/giphy.gif)

**Comment by Js41637** [comment]
![](http://i.imgur.com/MHuW96t.gif)

**Comment by jaruba** [comment]
this is serious though, guys..

![giphy 5](https://cloud.githubusercontent.com/assets/1777923/12281409/8e91a866-b99e-11e5-9006-6c6825eeb12c.gif)

**Comment by luigiplr** [comment]
> this is serious though

mrw:
![](http://www.hilariousgifs.com/gifs/rocket-snail.gif)

**Comment by KsaRedFx** [comment]
You said serious? 
![image](https://cloud.githubusercontent.com/assets/1790490/12281555/2c6173a8-b965-11e5-889d-600e4adcd657.png)
I'm so serious.

**Comment by jaruba** [comment]
we starting this party again?

![tumblr_ly5vgeme3g1qahroko1_500](https://cloud.githubusercontent.com/assets/1777923/12281568/0adb6aa0-b9a0-11e5-939e-516d5216a5d5.gif)

**Comment by luigiplr** [comment]
![](http://cdn.meme.am/instances/63906944.jpg)

**Comment by Js41637** [comment]
![](http://i.imgur.com/1HNTnVW.gif)
