### ISSUE TITLE
Avoid UAC prompt on startup [enhancement?]

### ISSUE THREAD

**Issue by rozza-m** [StrikeOrg/ulterius-server#40]
At best, a UAC prompt on _every_ startup is annoying and invokes negative perception of the product. Worst, in a headless or unmonitored situation, it can prevent other things/inputs from happening properly.

To fix, implement the server as a startup process or use task scheduler to start the bootstrapper on startup, which doesn't need a UAC prompt every time.

**Comment by andrewmd5** [comment]
Fixed. Thanks for the suggestion.
