### ISSUE TITLE
Task bar icon option: Check for Updates

### ISSUE THREAD

**Issue by Cyndro** [StrikeOrg/ulterius-server#42]
There should be an option to check for updates when right clicking the taskbar icon.

Also.. clicking on settings just brings up a windows dialog box asking how to open a .json file. Most users won't understand this. Choosing to open the file in Notepad is also very ugly. Settings needs a UI of some sort.

**Comment by andrewmd5** [comment]
Hi,

The server automatically updates itself when it is restarted, we will add information to the client that lets you know when an update is available. As for settings, all settings can be edited from inside the client. The JSON file is there for advanced users.
