### ISSUE TITLE
Server restart while no internet connection fails

### ISSUE THREAD

**Issue by Cyndro** [StrikeOrg/ulterius-server#47]
Hello!

Since I've been having hella internet issues lately I was able to randomly cross a problem with restarting Ulterius while no connection to the internet is available. The check for updates fails, throws an error and the restart won't continue until you click ok, and it won't finish until an internet connection is available again - not sure if it actually completes the check for update in the end as it just disappears when you hit ok.

http://imgur.com/mL2rIsB <-- the error message.

> Logs Ready
> Set Startup
> Loading Webcams
> 1 cameras loaded
> Setting up HTTP Server
> Web Server is running on this port: 22006
> Creating system service
> Error getting IP
> Unable to connect to the remote server
> File Database Ready
> Cron Daemon Started
> Api Server started at 0.0.0.0
> Starting Terminal API
> Connection from 127.0.0.1:50996
> Terminal Server bound to 0.0.0.0:22008
> Trying to forward ports
> Manager started for 22010
> Manager started for 22009
> UlteriusServer.TerminalServer.Messaging.TerminalControl.Requests.AesHandshakeRequest
> System.Threading.Tasks.TaskCanceledException: A task was canceled.
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at UlteriusServer.Api.Services.Update.ClientUpdateService.<CheckForUpdates>d__3.MoveNext() in D:\Documents\StrikeTaskManager\RemoteTaskServer\Api\Services\Update\ClientUpdateService.cs:line 86
> No NAT Device Found
> Starting notify icon

**Comment by andrewmd5** [comment]
Ah, this error should be more detailed, this means the connection between you and the api died. I will update it to continue if it encounters this problem.

For now, just run Ulterius Server.exe directly .

**Comment by andrewmd5** [comment]
This is fixed.
