### ISSUE TITLE
Using appveyor for CI

### ISSUE THREAD

**Issue by stephengroat** [StrikeOrg/ulterius-server#49]
Have you heard of/tried [appveyor](https://www.appveyor.com/)? Windows CI system that seems to work well.

Something Ulterius would be interested in?

I've done some work for Unicorn Engine to get it running, would be more than willing to help here too

**Comment by andrewmd5** [comment]
We have an internal build solution so this isn't very needed, however thank you for reaching out. 

If there are any other changes you'd like to discuss feel free to open another issue.  Looking forward to your future contributions.
