### ISSUE TITLE
Cannot install - reproducible on two computers

### ISSUE THREAD

**Issue by Taapo** [StrikeOrg/ulterius-server#58]
I was trying to install this on my Bootcamp MBP running Windows 8.1, but it didn't work. I had your installer install .NET and rebooted - after reboot I get the installation screen (like shown below) - and I check the agreement box. But when clicking the install button, nothing happens. I thought it would be something related to the retina screen, so I tried installing it on my Lenovo laptop - but it has the same exact problem. Is there something I'm missing?

![image](https://cloud.githubusercontent.com/assets/9305190/21294617/52b6a21a-c541-11e6-9976-415242716087.png)

**Comment by andrewmd5** [comment]
Hey sorry for the trouble, try downloading this installer and let me know if it works. I've thrown away the special theme since its obviously broken on most systems. 

https://ulterius.io/downloads/ulterius1.5.6.0beta.exe

**Comment by Taapo** [comment]
Thanks. That worked, but now I have another problem. The tray icon allows me to open the control panel, when I click open "client", I very briefly (just a millisecond) see the windows selection box to choose a browser to show the webpage it's trying to open. However, since it dissappears directly after showing the selection, I cannot open the client page. Is there something wrong?
