### ISSUE TITLE
No uninstall instructions

### ISSUE THREAD

**Issue by nickrod518** [StrikeOrg/ulterius-server#73]
Are there instructions on removing the server from a computer? I know there is a service, some stuff in AppData, but not sure what else.

**Comment by andrewmd5** [comment]
Running the uninstaller removes the service, AppData is left over because of auto-updating. That is it.

**Comment by nickrod518** [comment]
Thanks, I was looking in the folder next to the exe and in the Start menu. I didn't realize it was as simple as choosing "Remove" from the Add and Remove Programs menu!
