### ISSUE TITLE
Ulterius update - instalation was blocked

### ISSUE THREAD

**Issue by samsk** [StrikeOrg/ulterius-server#78]
With fresh installation of ulterius1.8.5.0beta, i get Ulterius update screen with Errror: Update installation was blocked.

![ulterius-update](https://user-images.githubusercontent.com/1709205/32445200-50631e90-c305-11e7-81a3-592a9be814ed.jpg)

**Comment by andrewmd5** [comment]
You'll need to manually remove that version and update to https://ulterius.io/downloads/ulterius1.9.5.0beta.exe

**Comment by samsk** [comment]
I've downloaded from github/releases and didn't know there is new version.
Ok, thanks. Great product ;)
